<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpMath.SkiaSharp" Version="1.0.0-pre.1" />
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.7" />
    <PackageReference Include="SkiaSharp" Version="3.119.3-preview.1.1" />
    <PackageReference Include="TextMateSharp" Version="1.0.70" />
    <PackageReference Include="TextMateSharp.Grammars" Version="1.0.70" />
  </ItemGroup>
    
  <ItemGroup>
    <Content Include="AUTHORS.md" />
    <Content Include="candlestick_mark_plan.md" />
    <Content Include="chart_animation_interaction_plan.md" />
    <Content Include="chart_demo_tabs_plan.md" />
    <Content Include="COMPONENTS.md" />
    <Content Include="Component\GodotChart\component_info.json" />
    <Content Include="README.md" />
  </ItemGroup>
</Project>