"""Generate the hyphenation pattern tables the engine ships with, from the TeX patterns (hyph-utf8).

Run from the repository root:

    python Tools/Typography/gen_hyphenation_tables.py --hyph-dir tmp/cache/hyph/src

The inputs are the plain-text variants the hyph-utf8 package ships next to the `.tex` ones:
`hyph-<lang>.pat.txt` (one pattern per line), the optional `hyph-<lang>.hyp.txt` (the TeX `\\hyphenation{}`
exceptions as hyphenated words), and `hyph-<lang>.tex` for the metadata the `.tex` header carries (version, licence,
the left and right minimum word lengths).

Each language becomes one `*.g.cs` file whose header records where the data came from, its version, its SHA-256 and
its licence - the same discipline the Unicode tables follow, plus the licence because hyph-utf8 collects pattern files
under different terms and each one has to be redistributable for its table to be in this repository.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

#: Languages to generate: (id, class name suffix, tag used in the file names).
LANGUAGES = [
    ("en-us", "EnUs", "en-us"),
    ("en-gb", "EnGb", "en-gb"),
    ("de-1996", "De1996", "de-1996"),
    ("fr", "Fr", "fr"),
]

VERSION_RE = re.compile(r"^%\s*version:\s*(.+)$", re.MULTILINE)
LEFT_RE = re.compile(r"^%\s*left:\s*(\d+)", re.MULTILINE)
RIGHT_RE = re.compile(r"^%\s*right:\s*(\d+)", re.MULTILINE)
LICENCE_RE = re.compile(r"^%\s*licence:\s*\n%\s*text:\s*>\s*\n((?:%\s{8}.*\n)+)", re.MULTILINE)


def read_licence(tex: str) -> str:
    """The licence text from a pattern file's header, as one line."""
    match = LICENCE_RE.search(tex)

    if match is None:
        return "see the hyph-utf8 package (licence not stated in the file header)"

    lines = [line.lstrip("%").strip() for line in match.group(1).splitlines()]
    return " ".join(part for part in lines if part)


def csharp_literal(text: str) -> str:
    """A C# string literal for the text, with the escapes a compiler needs and nothing else."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "\\n")
    return f'"{escaped}"'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--hyph-dir", default="tmp/cache/hyph/src", help="directory holding the hyph-utf8 text files")
    parser.add_argument("--out", default="Component/Typography/Core/Hyphenation", help="output directory")
    args = parser.parse_args()

    source_dir = Path(args.hyph_dir)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    for language_id, class_suffix, file_tag in LANGUAGES:
        patterns_path = source_dir / f"hyph-{file_tag}.pat.txt"
        tex_path = source_dir / f"hyph-{file_tag}.tex"
        exceptions_path = source_dir / f"hyph-{file_tag}.hyp.txt"

        if not patterns_path.exists() or not tex_path.exists():
            print(f"missing input for {language_id}: {patterns_path.name} / {tex_path.name}")
            return 1

        raw = patterns_path.read_bytes()
        patterns = [line.strip() for line in raw.decode("utf-8").splitlines() if line.strip()]

        exceptions: list[str] = []

        if exceptions_path.exists():
            exceptions = [
                line.strip()
                for line in exceptions_path.read_text(encoding="utf-8").splitlines()
                if line.strip() and not line.startswith("%")
            ]

        tex = tex_path.read_text(encoding="utf-8")
        version = (VERSION_RE.search(tex).group(1).strip() if VERSION_RE.search(tex) else "unknown")
        # The header may state the same values for more than one purpose (de-1996 has both a generation and a
        # typesetting block): the last one is the typesetting pair, which is what laying text out needs.
        left_matches = LEFT_RE.findall(tex)
        right_matches = RIGHT_RE.findall(tex)
        left = left_matches[-1] if left_matches else None
        right = right_matches[-1] if right_matches else None
        digest = hashlib.sha256(raw).hexdigest()
        licence = read_licence(tex)

        lines = [
            "// <auto-generated>",
            f"//     Generated by Tools/Typography/gen_hyphenation_tables.py from {patterns_path.name} (hyph-utf8 / TeX patterns).",
            f"//     Language: {language_id}",
            f"//     Version: {version}",
            f"//     Source SHA-256: {digest}",
            f"//     Licence: {licence}",
            "//     Do not edit; run the generator instead.",
            "// </auto-generated>",
            "",
            "namespace GodotNodeExtension.Component.Typography.Core.Hyphenation;",
            "",
            "/// <summary>",
            f"/// The {language_id} hyphenation patterns, as Liang's algorithm takes them: one pattern per line, where a digit",
            "/// between letters is the score of the gap it stands in (odd allows a break, even forbids one).",
            "/// </summary>",
            f"internal static class Hyphenation{class_suffix}",
            "{",
            f'    internal const string Id = "{language_id}";',
            f'    internal const string Source = "{patterns_path.name}";',
            f"    internal const string Version = {csharp_literal(version)};",
            f'    internal const string Sha256 = "{digest}";',
            f"    internal const string Licence = {csharp_literal(licence)};",
            "",
            "    /// <summary>Shortest word part allowed before a break.</summary>",
            f"    internal const int LeftMin = {left or 2};",
            "",
            "    /// <summary>Shortest word part allowed after a break.</summary>",
            f"    internal const int RightMin = {right or 2};",
            "",
            "    /// <summary>",
            "    /// The patterns, one per line.",
            "    /// </summary>",
            f"    internal const string PatternLines = {csharp_literal(chr(10).join(patterns))};",
            "",
            "    /// <summary>The exceptions the pattern file states, as hyphenated words.</summary>",
            f"    internal const string ExceptionLines = {csharp_literal(chr(10).join(exceptions))};",
            "}",
            "",
        ]

        target = out_dir / f"Hyphenation{class_suffix}.g.cs"
        target.write_text("\n".join(lines), encoding="utf-8", newline="\n")
        print(
            f"  {target.name}: {len(patterns)} patterns, {len(exceptions)} exceptions, "
            f"{target.stat().st_size // 1024} KB, version {version}, mins {left or 2}/{right or 2}"
        )

    print("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
