// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from DerivedBidiClass.txt
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>Values of the BidiClass property, as they appear in DerivedBidiClass.txt.</summary>
public enum BidiClassValue
{
    /// <summary>AL.</summary>
    AL,

    /// <summary>AN.</summary>
    AN,

    /// <summary>B.</summary>
    B,

    /// <summary>BN.</summary>
    BN,

    /// <summary>CS.</summary>
    CS,

    /// <summary>EN.</summary>
    EN,

    /// <summary>ES.</summary>
    ES,

    /// <summary>ET.</summary>
    ET,

    /// <summary>FSI.</summary>
    FSI,

    /// <summary>L.</summary>
    L,

    /// <summary>LRE.</summary>
    LRE,

    /// <summary>LRI.</summary>
    LRI,

    /// <summary>LRO.</summary>
    LRO,

    /// <summary>NSM.</summary>
    NSM,

    /// <summary>ON.</summary>
    ON,

    /// <summary>PDF.</summary>
    PDF,

    /// <summary>PDI.</summary>
    PDI,

    /// <summary>R.</summary>
    R,

    /// <summary>RLE.</summary>
    RLE,

    /// <summary>RLI.</summary>
    RLI,

    /// <summary>RLO.</summary>
    RLO,

    /// <summary>S.</summary>
    S,

    /// <summary>WS.</summary>
    WS,

}
