// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from EastAsianWidth.txt
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>Values of the EastAsianWidth property, as they appear in EastAsianWidth.txt.</summary>
public enum EastAsianWidthValue
{
    /// <summary>A.</summary>
    A,

    /// <summary>F.</summary>
    F,

    /// <summary>H.</summary>
    H,

    /// <summary>N.</summary>
    N,

    /// <summary>Na.</summary>
    Na,

    /// <summary>W.</summary>
    W,

}
