// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from emoji-data.txt
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>Values of the ExtendedPictographic property, as they appear in emoji-data.txt.</summary>
public enum ExtendedPictographicValue
{
    /// <summary>N.</summary>
    N,

    /// <summary>Y.</summary>
    Y,

}
