// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from emoji-data.txt
//     Unicode version: 17.0
//     Source SHA-256: 2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>
/// Unicode Extended_Pictographic property, used by UAX #14 (LB30b) and UAX #29 (WB3c).
/// <para>
/// Generated from <c>emoji-data.txt</c>, Unicode 17.0. Ranges are sorted and non-overlapping;
/// every code point the file does not list is <see cref="ExtendedPictographicValue.N"/>.
/// </para>
/// </summary>
public static class ExtendedPictographicData
{
    /// <summary>Unicode version of the data in this file.</summary>
    public const string UnicodeVersion = "17.0";

    /// <summary>SHA-256 of the source file, so a table can be traced back to its data.</summary>
    public const string SourceSha256 = "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b";

    /// <summary>Default value for code points the source file does not list.</summary>
    public const ExtendedPictographicValue Default = ExtendedPictographicValue.N;

    // [start, end, value] triples, sorted by start; the search is a binary search over Start.
    private static readonly int[] Starts =
    [
        0xA9, 0xAA, 0xAE, 0xAF, 0x203C, 0x203D, 0x2049, 0x204A, 0x2122, 0x2123, 0x2139, 0x213A,
        0x2194, 0x219A, 0x21A9, 0x21AB, 0x231A, 0x231C, 0x2328, 0x2329, 0x23CF, 0x23D0, 0x23E9, 0x23F4,
        0x23F8, 0x23FB, 0x24C2, 0x24C3, 0x25AA, 0x25AC, 0x25B6, 0x25B7, 0x25C0, 0x25C1, 0x25FB, 0x25FF,
        0x2600, 0x2605, 0x260E, 0x260F, 0x2611, 0x2612, 0x2614, 0x2616, 0x2618, 0x2619, 0x261D, 0x261E,
        0x2620, 0x2621, 0x2622, 0x2624, 0x2626, 0x2627, 0x262A, 0x262B, 0x262E, 0x2630, 0x2638, 0x263B,
        0x2640, 0x2641, 0x2642, 0x2643, 0x2648, 0x2654, 0x265F, 0x2661, 0x2663, 0x2664, 0x2665, 0x2667,
        0x2668, 0x2669, 0x267B, 0x267C, 0x267E, 0x2680, 0x2692, 0x2698, 0x2699, 0x269A, 0x269B, 0x269D,
        0x26A0, 0x26A2, 0x26A7, 0x26A8, 0x26AA, 0x26AC, 0x26B0, 0x26B2, 0x26BD, 0x26BF, 0x26C4, 0x26C6,
        0x26C8, 0x26C9, 0x26CE, 0x26D0, 0x26D1, 0x26D2, 0x26D3, 0x26D5, 0x26E9, 0x26EB, 0x26F0, 0x26F6,
        0x26F7, 0x26FB, 0x26FD, 0x26FE, 0x2702, 0x2703, 0x2705, 0x2706, 0x2708, 0x270E, 0x270F, 0x2710,
        0x2712, 0x2713, 0x2714, 0x2715, 0x2716, 0x2717, 0x271D, 0x271E, 0x2721, 0x2722, 0x2728, 0x2729,
        0x2733, 0x2735, 0x2744, 0x2745, 0x2747, 0x2748, 0x274C, 0x274D, 0x274E, 0x274F, 0x2753, 0x2756,
        0x2757, 0x2758, 0x2763, 0x2765, 0x2795, 0x2798, 0x27A1, 0x27A2, 0x27B0, 0x27B1, 0x27BF, 0x27C0,
        0x2934, 0x2936, 0x2B05, 0x2B08, 0x2B1B, 0x2B1D, 0x2B50, 0x2B51, 0x2B55, 0x2B56, 0x3030, 0x3031,
        0x303D, 0x303E, 0x3297, 0x3298, 0x3299, 0x329A, 0x1F004, 0x1F005, 0x1F02C, 0x1F030, 0x1F094, 0x1F0A0,
        0x1F0AF, 0x1F0B1, 0x1F0C0, 0x1F0C1, 0x1F0CF, 0x1F0D1, 0x1F0F6, 0x1F100, 0x1F170, 0x1F172, 0x1F17E, 0x1F180,
        0x1F18E, 0x1F18F, 0x1F191, 0x1F19B, 0x1F1AE, 0x1F1E6, 0x1F201, 0x1F210, 0x1F21A, 0x1F21B, 0x1F22F, 0x1F230,
        0x1F232, 0x1F23B, 0x1F23C, 0x1F240, 0x1F249, 0x1F260, 0x1F266, 0x1F322, 0x1F324, 0x1F394, 0x1F396, 0x1F398,
        0x1F399, 0x1F39C, 0x1F39E, 0x1F3F1, 0x1F3F3, 0x1F3F6, 0x1F3F7, 0x1F3FB, 0x1F400, 0x1F4FE, 0x1F4FF, 0x1F53E,
        0x1F549, 0x1F54F, 0x1F550, 0x1F568, 0x1F56F, 0x1F571, 0x1F573, 0x1F57B, 0x1F587, 0x1F588, 0x1F58A, 0x1F58E,
        0x1F590, 0x1F591, 0x1F595, 0x1F597, 0x1F5A4, 0x1F5A6, 0x1F5A8, 0x1F5A9, 0x1F5B1, 0x1F5B3, 0x1F5BC, 0x1F5BD,
        0x1F5C2, 0x1F5C5, 0x1F5D1, 0x1F5D4, 0x1F5DC, 0x1F5DF, 0x1F5E1, 0x1F5E2, 0x1F5E3, 0x1F5E4, 0x1F5E8, 0x1F5E9,
        0x1F5EF, 0x1F5F0, 0x1F5F3, 0x1F5F4, 0x1F5FA, 0x1F650, 0x1F680, 0x1F6C6, 0x1F6CB, 0x1F6D3, 0x1F6D5, 0x1F6E6,
        0x1F6E9, 0x1F6EA, 0x1F6EB, 0x1F6F1, 0x1F6F3, 0x1F700, 0x1F7DA, 0x1F800, 0x1F80C, 0x1F810, 0x1F848, 0x1F850,
        0x1F85A, 0x1F860, 0x1F888, 0x1F890, 0x1F8AE, 0x1F8B0, 0x1F8BC, 0x1F8C0, 0x1F8C2, 0x1F8D0, 0x1F8D9, 0x1F900,
        0x1F90C, 0x1F93B, 0x1F93C, 0x1F946, 0x1F947, 0x1FA00, 0x1FA58, 0x1FA60, 0x1FA6E, 0x1FB00, 0x1FC00,
    ];

    private static readonly int[] Ends =
    [
        0xA9, 0xAD, 0xAE, 0x203B, 0x203C, 0x2048, 0x2049, 0x2121, 0x2122, 0x2138, 0x2139, 0x2193,
        0x2199, 0x21A8, 0x21AA, 0x2319, 0x231B, 0x2327, 0x2328, 0x23CE, 0x23CF, 0x23E8, 0x23F3, 0x23F7,
        0x23FA, 0x24C1, 0x24C2, 0x25A9, 0x25AB, 0x25B5, 0x25B6, 0x25BF, 0x25C0, 0x25FA, 0x25FE, 0x25FF,
        0x2604, 0x260D, 0x260E, 0x2610, 0x2611, 0x2613, 0x2615, 0x2617, 0x2618, 0x261C, 0x261D, 0x261F,
        0x2620, 0x2621, 0x2623, 0x2625, 0x2626, 0x2629, 0x262A, 0x262D, 0x262F, 0x2637, 0x263A, 0x263F,
        0x2640, 0x2641, 0x2642, 0x2647, 0x2653, 0x265E, 0x2660, 0x2662, 0x2663, 0x2664, 0x2666, 0x2667,
        0x2668, 0x267A, 0x267B, 0x267D, 0x267F, 0x2691, 0x2697, 0x2698, 0x2699, 0x269A, 0x269C, 0x269F,
        0x26A1, 0x26A6, 0x26A7, 0x26A9, 0x26AB, 0x26AF, 0x26B1, 0x26BC, 0x26BE, 0x26C3, 0x26C5, 0x26C7,
        0x26C8, 0x26CD, 0x26CF, 0x26D0, 0x26D1, 0x26D2, 0x26D4, 0x26E8, 0x26EA, 0x26EF, 0x26F5, 0x26F6,
        0x26FA, 0x26FC, 0x26FD, 0x2701, 0x2702, 0x2704, 0x2705, 0x2707, 0x270D, 0x270E, 0x270F, 0x2711,
        0x2712, 0x2713, 0x2714, 0x2715, 0x2716, 0x271C, 0x271D, 0x2720, 0x2721, 0x2727, 0x2728, 0x2732,
        0x2734, 0x2743, 0x2744, 0x2746, 0x2747, 0x274B, 0x274C, 0x274D, 0x274E, 0x2752, 0x2755, 0x2756,
        0x2757, 0x2762, 0x2764, 0x2794, 0x2797, 0x27A0, 0x27A1, 0x27AF, 0x27B0, 0x27BE, 0x27BF, 0x2933,
        0x2935, 0x2B04, 0x2B07, 0x2B1A, 0x2B1C, 0x2B4F, 0x2B50, 0x2B54, 0x2B55, 0x302F, 0x3030, 0x303C,
        0x303D, 0x3296, 0x3297, 0x3298, 0x3299, 0x1F003, 0x1F004, 0x1F02B, 0x1F02F, 0x1F093, 0x1F09F, 0x1F0AE,
        0x1F0B0, 0x1F0BF, 0x1F0C0, 0x1F0CE, 0x1F0D0, 0x1F0F5, 0x1F0FF, 0x1F16F, 0x1F171, 0x1F17D, 0x1F17F, 0x1F18D,
        0x1F18E, 0x1F190, 0x1F19A, 0x1F1AD, 0x1F1E5, 0x1F200, 0x1F20F, 0x1F219, 0x1F21A, 0x1F22E, 0x1F22F, 0x1F231,
        0x1F23A, 0x1F23B, 0x1F23F, 0x1F248, 0x1F25F, 0x1F265, 0x1F321, 0x1F323, 0x1F393, 0x1F395, 0x1F397, 0x1F398,
        0x1F39B, 0x1F39D, 0x1F3F0, 0x1F3F2, 0x1F3F5, 0x1F3F6, 0x1F3FA, 0x1F3FF, 0x1F4FD, 0x1F4FE, 0x1F53D, 0x1F548,
        0x1F54E, 0x1F54F, 0x1F567, 0x1F56E, 0x1F570, 0x1F572, 0x1F57A, 0x1F586, 0x1F587, 0x1F589, 0x1F58D, 0x1F58F,
        0x1F590, 0x1F594, 0x1F596, 0x1F5A3, 0x1F5A5, 0x1F5A7, 0x1F5A8, 0x1F5B0, 0x1F5B2, 0x1F5BB, 0x1F5BC, 0x1F5C1,
        0x1F5C4, 0x1F5D0, 0x1F5D3, 0x1F5DB, 0x1F5DE, 0x1F5E0, 0x1F5E1, 0x1F5E2, 0x1F5E3, 0x1F5E7, 0x1F5E8, 0x1F5EE,
        0x1F5EF, 0x1F5F2, 0x1F5F3, 0x1F5F9, 0x1F64F, 0x1F67F, 0x1F6C5, 0x1F6CA, 0x1F6D2, 0x1F6D4, 0x1F6E5, 0x1F6E8,
        0x1F6E9, 0x1F6EA, 0x1F6F0, 0x1F6F2, 0x1F6FF, 0x1F7D9, 0x1F7FF, 0x1F80B, 0x1F80F, 0x1F847, 0x1F84F, 0x1F859,
        0x1F85F, 0x1F887, 0x1F88F, 0x1F8AD, 0x1F8AF, 0x1F8BB, 0x1F8BF, 0x1F8C1, 0x1F8CF, 0x1F8D8, 0x1F8FF, 0x1F90B,
        0x1F93A, 0x1F93B, 0x1F945, 0x1F946, 0x1F9FF, 0x1FA57, 0x1FA5F, 0x1FA6D, 0x1FAFF, 0x1FBFF, 0x1FFFD,
    ];

    private static readonly ExtendedPictographicValue[] Values =
    [
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N,
        ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y, ExtendedPictographicValue.N, ExtendedPictographicValue.Y,
    ];

    /// <summary>Look up the property value of a code point.</summary>
    /// <param name="codePoint">The code point to look up.</param>
    /// <returns>The value, or <see cref="ExtendedPictographicValue.N"/> when the code point is unassigned.</returns>
    public static ExtendedPictographicValue Lookup(int codePoint)
    {
        int low = 0;
        int high = Starts.Length - 1;

        while (low <= high)
        {
            int middle = (low + high) >> 1;

            if (codePoint < Starts[middle])
            {
                high = middle - 1;
            }
            else if (codePoint > Ends[middle])
            {
                low = middle + 1;
            }
            else
            {
                return Values[middle];
            }
        }

        return Default;
    }
}
