// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from LineBreak.txt
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>Values of the LineBreak property, as they appear in LineBreak.txt.</summary>
public enum LineBreakValue
{
    /// <summary>AI.</summary>
    AI,

    /// <summary>AK.</summary>
    AK,

    /// <summary>AL.</summary>
    AL,

    /// <summary>AP.</summary>
    AP,

    /// <summary>AS.</summary>
    AS,

    /// <summary>B.</summary>
    B,

    /// <summary>BA.</summary>
    BA,

    /// <summary>BB.</summary>
    BB,

    /// <summary>BK.</summary>
    BK,

    /// <summary>CB.</summary>
    CB,

    /// <summary>CJ.</summary>
    CJ,

    /// <summary>CL.</summary>
    CL,

    /// <summary>CM.</summary>
    CM,

    /// <summary>CP.</summary>
    CP,

    /// <summary>CR.</summary>
    CR,

    /// <summary>EB.</summary>
    EB,

    /// <summary>EM.</summary>
    EM,

    /// <summary>EX.</summary>
    EX,

    /// <summary>GL.</summary>
    GL,

    /// <summary>H.</summary>
    H,

    /// <summary>HH.</summary>
    HH,

    /// <summary>HL.</summary>
    HL,

    /// <summary>HY.</summary>
    HY,

    /// <summary>ID.</summary>
    ID,

    /// <summary>IN.</summary>
    IN,

    /// <summary>IS.</summary>
    IS,

    /// <summary>JL.</summary>
    JL,

    /// <summary>JT.</summary>
    JT,

    /// <summary>JV.</summary>
    JV,

    /// <summary>LF.</summary>
    LF,

    /// <summary>NL.</summary>
    NL,

    /// <summary>NS.</summary>
    NS,

    /// <summary>NU.</summary>
    NU,

    /// <summary>OP.</summary>
    OP,

    /// <summary>PO.</summary>
    PO,

    /// <summary>PR.</summary>
    PR,

    /// <summary>QU.</summary>
    QU,

    /// <summary>RI.</summary>
    RI,

    /// <summary>SA.</summary>
    SA,

    /// <summary>SG.</summary>
    SG,

    /// <summary>SP.</summary>
    SP,

    /// <summary>SY.</summary>
    SY,

    /// <summary>VF.</summary>
    VF,

    /// <summary>VI.</summary>
    VI,

    /// <summary>WJ.</summary>
    WJ,

    /// <summary>XX.</summary>
    XX,

    /// <summary>ZW.</summary>
    ZW,

    /// <summary>ZWJ.</summary>
    ZWJ,

}
