// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from Scripts.txt
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>Values of the Script property, as they appear in Scripts.txt.</summary>
public enum ScriptValue
{
    /// <summary>Adlam.</summary>
    Adlam,

    /// <summary>Ahom.</summary>
    Ahom,

    /// <summary>Anatolian_Hieroglyphs.</summary>
    Anatolian_Hieroglyphs,

    /// <summary>Arabic.</summary>
    Arabic,

    /// <summary>Armenian.</summary>
    Armenian,

    /// <summary>Avestan.</summary>
    Avestan,

    /// <summary>Balinese.</summary>
    Balinese,

    /// <summary>Bamum.</summary>
    Bamum,

    /// <summary>Bassa_Vah.</summary>
    Bassa_Vah,

    /// <summary>Batak.</summary>
    Batak,

    /// <summary>Bengali.</summary>
    Bengali,

    /// <summary>Beria_Erfe.</summary>
    Beria_Erfe,

    /// <summary>Bhaiksuki.</summary>
    Bhaiksuki,

    /// <summary>Bopomofo.</summary>
    Bopomofo,

    /// <summary>Brahmi.</summary>
    Brahmi,

    /// <summary>Braille.</summary>
    Braille,

    /// <summary>Buginese.</summary>
    Buginese,

    /// <summary>Buhid.</summary>
    Buhid,

    /// <summary>Canadian_Aboriginal.</summary>
    Canadian_Aboriginal,

    /// <summary>Carian.</summary>
    Carian,

    /// <summary>Caucasian_Albanian.</summary>
    Caucasian_Albanian,

    /// <summary>Chakma.</summary>
    Chakma,

    /// <summary>Cham.</summary>
    Cham,

    /// <summary>Cherokee.</summary>
    Cherokee,

    /// <summary>Chorasmian.</summary>
    Chorasmian,

    /// <summary>Common.</summary>
    Common,

    /// <summary>Coptic.</summary>
    Coptic,

    /// <summary>Cuneiform.</summary>
    Cuneiform,

    /// <summary>Cypriot.</summary>
    Cypriot,

    /// <summary>Cypro_Minoan.</summary>
    Cypro_Minoan,

    /// <summary>Cyrillic.</summary>
    Cyrillic,

    /// <summary>Deseret.</summary>
    Deseret,

    /// <summary>Devanagari.</summary>
    Devanagari,

    /// <summary>Dives_Akuru.</summary>
    Dives_Akuru,

    /// <summary>Dogra.</summary>
    Dogra,

    /// <summary>Duployan.</summary>
    Duployan,

    /// <summary>Egyptian_Hieroglyphs.</summary>
    Egyptian_Hieroglyphs,

    /// <summary>Elbasan.</summary>
    Elbasan,

    /// <summary>Elymaic.</summary>
    Elymaic,

    /// <summary>Ethiopic.</summary>
    Ethiopic,

    /// <summary>Garay.</summary>
    Garay,

    /// <summary>Georgian.</summary>
    Georgian,

    /// <summary>Glagolitic.</summary>
    Glagolitic,

    /// <summary>Gothic.</summary>
    Gothic,

    /// <summary>Grantha.</summary>
    Grantha,

    /// <summary>Greek.</summary>
    Greek,

    /// <summary>Gujarati.</summary>
    Gujarati,

    /// <summary>Gunjala_Gondi.</summary>
    Gunjala_Gondi,

    /// <summary>Gurmukhi.</summary>
    Gurmukhi,

    /// <summary>Gurung_Khema.</summary>
    Gurung_Khema,

    /// <summary>Han.</summary>
    Han,

    /// <summary>Hangul.</summary>
    Hangul,

    /// <summary>Hanifi_Rohingya.</summary>
    Hanifi_Rohingya,

    /// <summary>Hanunoo.</summary>
    Hanunoo,

    /// <summary>Hatran.</summary>
    Hatran,

    /// <summary>Hebrew.</summary>
    Hebrew,

    /// <summary>Hiragana.</summary>
    Hiragana,

    /// <summary>Imperial_Aramaic.</summary>
    Imperial_Aramaic,

    /// <summary>Inherited.</summary>
    Inherited,

    /// <summary>Inscriptional_Pahlavi.</summary>
    Inscriptional_Pahlavi,

    /// <summary>Inscriptional_Parthian.</summary>
    Inscriptional_Parthian,

    /// <summary>Javanese.</summary>
    Javanese,

    /// <summary>Kaithi.</summary>
    Kaithi,

    /// <summary>Kannada.</summary>
    Kannada,

    /// <summary>Katakana.</summary>
    Katakana,

    /// <summary>Kawi.</summary>
    Kawi,

    /// <summary>Kayah_Li.</summary>
    Kayah_Li,

    /// <summary>Kharoshthi.</summary>
    Kharoshthi,

    /// <summary>Khitan_Small_Script.</summary>
    Khitan_Small_Script,

    /// <summary>Khmer.</summary>
    Khmer,

    /// <summary>Khojki.</summary>
    Khojki,

    /// <summary>Khudawadi.</summary>
    Khudawadi,

    /// <summary>Kirat_Rai.</summary>
    Kirat_Rai,

    /// <summary>Lao.</summary>
    Lao,

    /// <summary>Latin.</summary>
    Latin,

    /// <summary>Lepcha.</summary>
    Lepcha,

    /// <summary>Limbu.</summary>
    Limbu,

    /// <summary>Linear_A.</summary>
    Linear_A,

    /// <summary>Linear_B.</summary>
    Linear_B,

    /// <summary>Lisu.</summary>
    Lisu,

    /// <summary>Lycian.</summary>
    Lycian,

    /// <summary>Lydian.</summary>
    Lydian,

    /// <summary>Mahajani.</summary>
    Mahajani,

    /// <summary>Makasar.</summary>
    Makasar,

    /// <summary>Malayalam.</summary>
    Malayalam,

    /// <summary>Mandaic.</summary>
    Mandaic,

    /// <summary>Manichaean.</summary>
    Manichaean,

    /// <summary>Marchen.</summary>
    Marchen,

    /// <summary>Masaram_Gondi.</summary>
    Masaram_Gondi,

    /// <summary>Medefaidrin.</summary>
    Medefaidrin,

    /// <summary>Meetei_Mayek.</summary>
    Meetei_Mayek,

    /// <summary>Mende_Kikakui.</summary>
    Mende_Kikakui,

    /// <summary>Meroitic_Cursive.</summary>
    Meroitic_Cursive,

    /// <summary>Meroitic_Hieroglyphs.</summary>
    Meroitic_Hieroglyphs,

    /// <summary>Miao.</summary>
    Miao,

    /// <summary>Modi.</summary>
    Modi,

    /// <summary>Mongolian.</summary>
    Mongolian,

    /// <summary>Mro.</summary>
    Mro,

    /// <summary>Multani.</summary>
    Multani,

    /// <summary>Myanmar.</summary>
    Myanmar,

    /// <summary>Nabataean.</summary>
    Nabataean,

    /// <summary>Nag_Mundari.</summary>
    Nag_Mundari,

    /// <summary>Nandinagari.</summary>
    Nandinagari,

    /// <summary>New_Tai_Lue.</summary>
    New_Tai_Lue,

    /// <summary>Newa.</summary>
    Newa,

    /// <summary>Nko.</summary>
    Nko,

    /// <summary>Nushu.</summary>
    Nushu,

    /// <summary>Nyiakeng_Puachue_Hmong.</summary>
    Nyiakeng_Puachue_Hmong,

    /// <summary>Ogham.</summary>
    Ogham,

    /// <summary>Ol_Chiki.</summary>
    Ol_Chiki,

    /// <summary>Ol_Onal.</summary>
    Ol_Onal,

    /// <summary>Old_Hungarian.</summary>
    Old_Hungarian,

    /// <summary>Old_Italic.</summary>
    Old_Italic,

    /// <summary>Old_North_Arabian.</summary>
    Old_North_Arabian,

    /// <summary>Old_Permic.</summary>
    Old_Permic,

    /// <summary>Old_Persian.</summary>
    Old_Persian,

    /// <summary>Old_Sogdian.</summary>
    Old_Sogdian,

    /// <summary>Old_South_Arabian.</summary>
    Old_South_Arabian,

    /// <summary>Old_Turkic.</summary>
    Old_Turkic,

    /// <summary>Old_Uyghur.</summary>
    Old_Uyghur,

    /// <summary>Oriya.</summary>
    Oriya,

    /// <summary>Osage.</summary>
    Osage,

    /// <summary>Osmanya.</summary>
    Osmanya,

    /// <summary>Pahawh_Hmong.</summary>
    Pahawh_Hmong,

    /// <summary>Palmyrene.</summary>
    Palmyrene,

    /// <summary>Pau_Cin_Hau.</summary>
    Pau_Cin_Hau,

    /// <summary>Phags_Pa.</summary>
    Phags_Pa,

    /// <summary>Phoenician.</summary>
    Phoenician,

    /// <summary>Psalter_Pahlavi.</summary>
    Psalter_Pahlavi,

    /// <summary>Rejang.</summary>
    Rejang,

    /// <summary>Runic.</summary>
    Runic,

    /// <summary>Samaritan.</summary>
    Samaritan,

    /// <summary>Saurashtra.</summary>
    Saurashtra,

    /// <summary>Sharada.</summary>
    Sharada,

    /// <summary>Shavian.</summary>
    Shavian,

    /// <summary>Siddham.</summary>
    Siddham,

    /// <summary>Sidetic.</summary>
    Sidetic,

    /// <summary>SignWriting.</summary>
    SignWriting,

    /// <summary>Sinhala.</summary>
    Sinhala,

    /// <summary>Sogdian.</summary>
    Sogdian,

    /// <summary>Sora_Sompeng.</summary>
    Sora_Sompeng,

    /// <summary>Soyombo.</summary>
    Soyombo,

    /// <summary>Sundanese.</summary>
    Sundanese,

    /// <summary>Sunuwar.</summary>
    Sunuwar,

    /// <summary>Syloti_Nagri.</summary>
    Syloti_Nagri,

    /// <summary>Syriac.</summary>
    Syriac,

    /// <summary>Tagalog.</summary>
    Tagalog,

    /// <summary>Tagbanwa.</summary>
    Tagbanwa,

    /// <summary>Tai_Le.</summary>
    Tai_Le,

    /// <summary>Tai_Tham.</summary>
    Tai_Tham,

    /// <summary>Tai_Viet.</summary>
    Tai_Viet,

    /// <summary>Tai_Yo.</summary>
    Tai_Yo,

    /// <summary>Takri.</summary>
    Takri,

    /// <summary>Tamil.</summary>
    Tamil,

    /// <summary>Tangsa.</summary>
    Tangsa,

    /// <summary>Tangut.</summary>
    Tangut,

    /// <summary>Telugu.</summary>
    Telugu,

    /// <summary>Thaana.</summary>
    Thaana,

    /// <summary>Thai.</summary>
    Thai,

    /// <summary>Tibetan.</summary>
    Tibetan,

    /// <summary>Tifinagh.</summary>
    Tifinagh,

    /// <summary>Tirhuta.</summary>
    Tirhuta,

    /// <summary>Todhri.</summary>
    Todhri,

    /// <summary>Tolong_Siki.</summary>
    Tolong_Siki,

    /// <summary>Toto.</summary>
    Toto,

    /// <summary>Tulu_Tigalari.</summary>
    Tulu_Tigalari,

    /// <summary>Ugaritic.</summary>
    Ugaritic,

    /// <summary>Unknown.</summary>
    Unknown,

    /// <summary>Vai.</summary>
    Vai,

    /// <summary>Vithkuqi.</summary>
    Vithkuqi,

    /// <summary>Wancho.</summary>
    Wancho,

    /// <summary>Warang_Citi.</summary>
    Warang_Citi,

    /// <summary>Yezidi.</summary>
    Yezidi,

    /// <summary>Yi.</summary>
    Yi,

    /// <summary>Zanabazar_Square.</summary>
    Zanabazar_Square,

}
