// <auto-generated>
//     Generated by Tools/Typography/gen_unicode_tables.py from WordBreakProperty.txt
//     Do not edit by hand: re-run the generator instead.
// </auto-generated>

namespace GodotNodeExtension.Component.Typography.Core.Unicode;

/// <summary>Values of the WordBreak property, as they appear in WordBreakProperty.txt.</summary>
public enum WordBreakValue
{
    /// <summary>ALetter.</summary>
    ALetter,

    /// <summary>CR.</summary>
    CR,

    /// <summary>Double_Quote.</summary>
    Double_Quote,

    /// <summary>Extend.</summary>
    Extend,

    /// <summary>ExtendNumLet.</summary>
    ExtendNumLet,

    /// <summary>Format.</summary>
    Format,

    /// <summary>Hebrew_Letter.</summary>
    Hebrew_Letter,

    /// <summary>Katakana.</summary>
    Katakana,

    /// <summary>LF.</summary>
    LF,

    /// <summary>MidLetter.</summary>
    MidLetter,

    /// <summary>MidNum.</summary>
    MidNum,

    /// <summary>MidNumLet.</summary>
    MidNumLet,

    /// <summary>Newline.</summary>
    Newline,

    /// <summary>Numeric.</summary>
    Numeric,

    /// <summary>Other.</summary>
    Other,

    /// <summary>Regional_Indicator.</summary>
    Regional_Indicator,

    /// <summary>Single_Quote.</summary>
    Single_Quote,

    /// <summary>WSegSpace.</summary>
    WSegSpace,

    /// <summary>ZWJ.</summary>
    ZWJ,

}
